//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektrnika 2011
//http://www.mikroe.com

//GLCD FontName : myriad_pro_semibold11x16
//GLCD FontSize : 11 x 16

#ifndef FONTS_H_
#define FONTS_H_

#include <stdint.h>

extern const uint8_t myriad_pro_semibold_12[];
extern const uint8_t myriad_pro_semibold_16[];
extern const uint8_t myriad_pro_semibold_24[];

extern const uint8_t myriad_pro_bold_20[];

extern const uint8_t fontawesome_16[];
extern const uint8_t fontawesome_ecg[];
extern const uint8_t fontawesome_h2h[];
extern const uint8_t fontawesome_settings[];
extern const uint8_t fontawesome_back[];

#endif /* FONTS_H_ */