//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektrnika 2011 
//http://www.mikroe.com 

//GLCD FontName : myriad_pro_semibold11x16
//GLCD FontSize : 11 x 16

#ifndef MYRIAD_PRO_SEMIBOLD_H_
#define MYRIAD_PRO_SEMIBOLD_H_

#include <stdint.h>

extern const uint8_t myriad_pro_semibold11x16[];
extern const uint8_t myriad_pro_semibold17x23[];
extern const uint8_t myriad_pro_semibold28x39_num[];

#endif /* MYRIAD_PRO_SEMIBOLD_H_ */